In [ ]:
from google_drive_downloader import GoogleDriveDownloader as gdd

gdd.download_file_from_google_drive(file_id='1G_Ix97_JP5NhcmMY74ctA2piDxbiU1Lk',
dest_path='content/weather.zip',
unzip=True)

In [ ]:
import pandas as pd # Data analysis and manipultion tool
import numpy as np # Fundamental package for linear algebra and multidimensional arrays
import tensorflow as tf # Deep Learning Tool
import os # OS module in Python provides a way of using operating system dependent functionality
import cv2 # Library for image processing
from sklearn.model_selection import train_test_split # For splitting the data into train and validation set

In [ ]:
from google.colab import files
uploaded = files.upload()



Saving Training_set.csv to Training_set (2).csv


In [ ]:
import io
labels = pd.read_csv(io.BytesIO(uploaded['Training_set.csv']))
labels.head()

filename    label
0  Image_1.jpg  sunrise
1  Image_2.jpg    shine
2  Image_3.jpg   cloudy
3  Image_4.jpg    shine
4  Image_5.jpg  sunrise

In [ ]:
labels.tail() # will display the last five rows in labels dataframe


filename    label
1043  Image_1044.jpg    foggy
1044  Image_1045.jpg  sunrise
1045  Image_1046.jpg   cloudy
1046  Image_1047.jpg    rainy
1047  Image_1048.jpg  sunrise

In [ ]:
file_paths = [[fname, "/content/drive/MyDrive/dphi_data/" + fname] for fname in labels['filename']]


In [ ]:
# Confirm if number of images is same as number of labels given
if len(labels) == len(file_paths):
  print('Number of labels i.e. ', len(labels), 'matches the number of filenames i.e. ', len(file_paths))
else:
  print('Number of labels does not match the number of filenames')

Number of labels i.e.  1048 matches the number of filenames i.e.  1048


In [ ]:
images = pd.DataFrame(file_paths, columns=['filename', 'filepaths'])
images.head(25)

filename                                      filepaths
0    Image_1.jpg   /content/drive/MyDrive/dphi_data/Image_1.jpg
1    Image_2.jpg   /content/drive/MyDrive/dphi_data/Image_2.jpg
2    Image_3.jpg   /content/drive/MyDrive/dphi_data/Image_3.jpg
3    Image_4.jpg   /content/drive/MyDrive/dphi_data/Image_4.jpg
4    Image_5.jpg   /content/drive/MyDrive/dphi_data/Image_5.jpg
5    Image_6.jpg   /content/drive/MyDrive/dphi_data/Image_6.jpg
6    Image_7.jpg   /content/drive/MyDrive/dphi_data/Image_7.jpg
7    Image_8.jpg   /content/drive/MyDrive/dphi_data/Image_8.jpg
8    Image_9.jpg   /content/drive/MyDrive/dphi_data/Image_9.jpg
9   Image_10.jpg  /content/drive/MyDrive/dphi_data/Image_10.jpg
10  Image_11.jpg  /content/drive/MyDrive/dphi_data/Image_11.jpg
11  Image_12.jpg  /content/drive/MyDrive/dphi_data/Image_12.jpg
12  Image_13.jpg  /content/drive/MyDrive/dphi_data/Image_13.jpg
13  Image_14.jpg  /content/drive/MyDrive/dphi_data/Image_14.jpg
14  Image_15.jpg  /content/drive/MyDrive/dphi_data/Image_15.jpg
15  Image_16.jpg  /content/drive/MyDrive/dphi_data/Image_16.jpg
16  Image_17.jpg  /content/drive/MyDrive/dphi_data/Image_17.jpg
17  Image_18.jpg  /content/drive/MyDrive/dphi_data/Image_18.jpg
18  Image_19.jpg  /content/drive/MyDrive/dphi_data/Image_19.jpg
19  Image_20.jpg  /content/drive/MyDrive/dphi_data/Image_20.jpg
20  Image_21.jpg  /content/drive/MyDrive/dphi_data/Image_21.jpg
21  Image_22.jpg  /content/drive/MyDrive/dphi_data/Image_22.jpg
22  Image_23.jpg  /content/drive/MyDrive/dphi_data/Image_23.jpg
23  Image_24.jpg  /content/drive/MyDrive/dphi_data/Image_24.jpg
24  Image_25.jpg  /content/drive/MyDrive/dphi_data/Image_25.jpg

In [ ]:
train_data = pd.merge(images, labels, how = 'inner', on = 'filename')
train_data.head()

filename                                     filepaths    label
0  Image_1.jpg  /content/drive/MyDrive/dphi_data/Image_1.jpg  sunrise
1  Image_2.jpg  /content/drive/MyDrive/dphi_data/Image_2.jpg    shine
2  Image_3.jpg  /content/drive/MyDrive/dphi_data/Image_3.jpg   cloudy
3  Image_4.jpg  /content/drive/MyDrive/dphi_data/Image_4.jpg    shine
4  Image_5.jpg  /content/drive/MyDrive/dphi_data/Image_5.jpg  sunrise

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
train_data['label'] = le.fit_transform(train_data['label'])


In [ ]:
print(train_data[:5])

      filename                                     filepaths  label
0  Image_1.jpg  /content/drive/MyDrive/dphi_data/Image_1.jpg      4
1  Image_2.jpg  /content/drive/MyDrive/dphi_data/Image_2.jpg      3
2  Image_3.jpg  /content/drive/MyDrive/dphi_data/Image_3.jpg      0
3  Image_4.jpg  /content/drive/MyDrive/dphi_data/Image_4.jpg      3
4  Image_5.jpg  /content/drive/MyDrive/dphi_data/Image_5.jpg      4


In [ ]:

data = [] # initialize an empty numpy array
image_size = 100 # image size taken is 100 here. one can take other size too
for i in range(len(train_data)):

  img_array = cv2.imread(train_data['filepaths'][i]) # converting the image to gray scale
  square_img_array = cv2.resize(img_array, (image_size, image_size), interpolation = cv2.INTER_NEAREST) # resizing the image array
  data.append([square_img_array, train_data['label'][i]])

In [ ]:
len(data)

1048

In [ ]:
np.random.shuffle(data)


In [ ]:
x = []
y = []
for image in data:
  x.append(image[0])
  y.append(image[1])

# converting x & y to numpy array as they are list
x = np.array(x)
y = np.array(y)

In [ ]:
np.unique(y, return_counts=True)


(array([0, 1, 2, 3, 4]), array([210, 210, 209, 174, 245]))

In [ ]:
x = x.reshape(-1, image_size, image_size, 3)


In [ ]:
x=x/255
print(x[0].shape, x[0][1])

(100, 100, 3) [[0.99607843 0.58431373 0.3372549 ]
 [0.99607843 0.58431373 0.3372549 ]
 [0.99607843 0.58431373 0.3372549 ]
 [1.         0.58431373 0.3372549 ]
 [0.99215686 0.57647059 0.32941176]
 [0.99215686 0.57647059 0.32941176]
 [0.99215686 0.57647059 0.32941176]
 [1.         0.57254902 0.32941176]
 [0.99607843 0.56470588 0.32941176]
 [0.99607843 0.56470588 0.32941176]
 [0.99607843 0.56470588 0.32941176]
 [0.99215686 0.56078431 0.3254902 ]
 [0.99215686 0.56078431 0.3254902 ]
 [0.99215686 0.56078431 0.3254902 ]
 [0.99215686 0.56078431 0.3254902 ]
 [1.         0.56078431 0.3254902 ]
 [0.99607843 0.56470588 0.3372549 ]
 [0.99215686 0.56862745 0.34117647]
 [1.         0.57647059 0.35686275]
 [1.         0.57647059 0.35686275]
 [1.         0.57254902 0.36078431]
 [0.99607843 0.56862745 0.35686275]
 [0.99607843 0.56470588 0.36078431]
 [0.99607843 0.56470588 0.36078431]
 [0.99607843 0.56470588 0.36078431]
 [1.         0.56862745 0.36470588]
 [1.         0.56862745 0.36470588]
 [1.         0

In [ ]:
X_train, X_val, y_train, y_val = train_test_split(x,y,test_size=0.2, random_state = 432)


In [ ]:
cnn = tf.keras.models.Sequential([
tf.keras.layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu', input_shape=(image_size, image_size, 3)),
tf.keras.layers.MaxPooling2D((2, 2)),

tf.keras.layers.Conv2D(filters=44, kernel_size=(3, 3), activation='relu'),
tf.keras.layers.MaxPooling2D((2, 2)),

# tf.keras.layers.Flatten(input_shape=(100, 100, 1)),
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(72, activation='tanh'),
tf.keras.layers.Dense(32, activation='relu'),
tf.keras.layers.Dense(5, activation='softmax')
])


In [ ]:
cnn.compile(optimizer='Adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy'])

In [ ]:
cnn.fit(X_train, y_train, epochs=20, batch_size=1048)


Epoch 1/20
1/1 [==============================] - 20s 20s/step - loss: 0.2589 - accuracy: 0.9177
Epoch 2/20
1/1 [==============================] - 17s 17s/step - loss: 0.2669 - accuracy: 0.9200
Epoch 3/20
1/1 [==============================] - 17s 17s/step - loss: 0.2378 - accuracy: 0.9320
Epoch 4/20
1/1 [==============================] - 24s 24s/step - loss: 0.2435 - accuracy: 0.9189
Epoch 5/20
1/1 [==============================] - 17s 17s/step - loss: 0.2235 - accuracy: 0.9463
Epoch 6/20
1/1 [==============================] - 17s 17s/step - loss: 0.2271 - accuracy: 0.9439
Epoch 7/20
1/1 [==============================] - 17s 17s/step - loss: 0.2119 - accuracy: 0.9391
Epoch 8/20
1/1 [==============================] - 17s 17s/step - loss: 0.2100 - accuracy: 0.9391
Epoch 9/20
1/1 [==============================] - 17s 17s/step - loss: 0.2023 - accuracy: 0.9535
Epoch 10/20
1/1 [==============================] - 17s 17s/step - loss: 0.1919 - accuracy: 0.9547
Epoch 11/20
1/1 [============

In [ ]:
cnn.evaluate(X_val, y_val)


7/7 [==============================] - 1s 194ms/step - loss: 0.4868 - accuracy: 0.8143


[0.48679566383361816, 0.8142856955528259]

In [ ]:
from google.colab import files
uploaded = files.upload()



Saving Testing_set.csv to Testing_set.csv


In [ ]:
import io
test_image_order = pd.read_csv(io.BytesIO(uploaded['Testing_set.csv']))
test_image_order.head()

filename
0  Image_1.jpg
1  Image_2.jpg
2  Image_3.jpg
3  Image_4.jpg
4  Image_5.jpg

In [ ]:
file_paths = [[fname, '/content/drive/MyDrive/dphi_data/testdata/' + fname] for fname in test_image_order['filename']]


In [ ]:
# Confirm if number of images is same as number of labels given
if len(test_image_order) == len(file_paths):
  print('Number of image names i.e. ', len(test_image_order), 'matches the number of file paths i.e. ', len(file_paths))
else:
  print('Number of image names does not match the number of filepaths')


Number of image names i.e.  450 matches the number of file paths i.e.  450


In [ ]:
test_images = pd.DataFrame(file_paths, columns=['filename', 'filepaths'])
test_images.head()

filename                                          filepaths
0  Image_1.jpg  /content/drive/MyDrive/dphi_data/testdata/Imag...
1  Image_2.jpg  /content/drive/MyDrive/dphi_data/testdata/Imag...
2  Image_3.jpg  /content/drive/MyDrive/dphi_data/testdata/Imag...
3  Image_4.jpg  /content/drive/MyDrive/dphi_data/testdata/Imag...
4  Image_5.jpg  /content/drive/MyDrive/dphi_data/testdata/Imag...

In [ ]:
test_pixel_data = [] # initialize an empty numpy array
image_size = 50 # image size taken is 100 here. one can take other size too
for i in range(len(test_images)):

  img_array = cv2.imread(test_images['filepaths'][i]) # converting the image to gray scale

  new_img_array = cv2.resize(img_array, (image_size, image_size), interpolation = cv2.INTER_NEAREST) # resizing the image array

  test_pixel_data.append(new_img_array)

In [ ]:
test_pixel_data = np.array(test_pixel_data)


In [ ]:
test_pixel_data = test_pixel_data.reshape(-1, 50, 50, 3)
test_pixel_data=test_pixel_data/255
test_pixel_data

array([[[[0.05882353, 0.04705882, 0.01568627],
         [0.06666667, 0.04313725, 0.02352941],
         [0.0627451 , 0.03529412, 0.02352941],
         ...,
         [0.03137255, 0.02352941, 0.01960784],
         [0.19607843, 0.16862745, 0.07058824],
         [0.03921569, 0.03137255, 0.02745098]],

        [[0.0745098 , 0.04313725, 0.01568627],
         [0.08627451, 0.05490196, 0.02745098],
         [0.09019608, 0.04705882, 0.03137255],
         ...,
         [0.02745098, 0.01960784, 0.01568627],
         [0.18823529, 0.16078431, 0.08627451],
         [0.03921569, 0.03137255, 0.03137255]],

        [[0.14901961, 0.08627451, 0.02352941],
         [0.15686275, 0.09411765, 0.04313725],
         [0.14117647, 0.0745098 , 0.02352941],
         ...,
         [0.04705882, 0.03137255, 0.02745098],
         [0.03137255, 0.02352941, 0.02352941],
         [0.03137255, 0.02352941, 0.02352941]],

        ...,

        [[0.09803922, 0.25098039, 0.37647059],
         [0.10588235, 0.08627451, 0.09019608]

In [ ]:
pred = cnn.predict(test_pixel_data)


In [ ]:
pred[0]
prediction = []
for value in pred:
  prediction.append(np.argmax(value))

In [ ]:
predictions = le.inverse_transform(prediction)


In [ ]:
res = pd.DataFrame({'filename': test_images['filename'], 'label': predictions}) # prediction is nothing but the final predictions of your model on input features of your new unseen test data
res.to_csv("submission.csv", index = False)

# To download the csv file locally
from google.colab import files
files.download('submission.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>